image:
  file: .gitpod.Dockerfile
ports:
  - port: 8000
    onOpen: open-preview
vscode:
  extensions:
    - rust-lang.rust@0.7.8:CvNqMTgDdt3UXt+6BCDTVg==
    - JakeBecker.elixir-ls@0.2.25:X1tqg5Hmluq055QJpf0/7A==
    - mjmcloug.vscode-elixir@1.1.0:w8GjsJyyhVFmCZmBc2Ws7A==
    - pgourlain.erlang@0.6.2:jRQAb13xJ5s36YhjamDdag==
    - elixir-lsp.elixir-ls@0.6.2:j/OgOgkgo0QJRBdZXhmoUQ==